### ISSUE TITLE
Curate a OFE group ID

### ISSUE THREAD

**Issue by akrherz** [dailyerosion/dep#298]
@dejames52 and @edulukin have been patiently waiting for me to do some analysis of what they called an `uniqueid` to classify our DEP OFEs into comparable groups.  I'd rather not call this value `uniqueid` as that implies something it is not.  I'll instead call it a `groupid` and it will be represented by an underscore seperated string of values in the form `<slopeclass>_<kwfactclass>_<tillagecode>_<genlandusecode>` where

**slopeclass** is

Bulk slope % | class
--- | ---
0 <= x <= 0.02 | 1
0.02 < x <= 0.04 | 2
0.04 < x <= 0.06 | 3
0.06 < x <= 0.12 | 4
0.12 < x | 5

**kwfactclass** is

kwfact | class
--- | ---
0 < x <= 0.28 | 1
0.28 < x <= 0.32 | 2
0.32 < x | 3

`tillagecode` and `genlandusecode` are verbatim.

# TODO

- [ ] create database storage
- [ ] assign these at import time
- [ ] update current database entries with these

**Comment by akrherz** [comment]
The SQL run to update the current entries

```sql
update flowpath_ofes o
SET groupid = case when bulk_slope <= 0.02 then 1 when bulk_slope <= 0.04 then 2 when bulk_slope <= 0.06 then 3 when bulk_slope <= 0.12 then 4 else 5 end
||'_'|| case when kwfact <= 0.28 then 1 when kwfact <= 0.32 then 2 else 3 end 
||'_'|| substr(f.management, 1, 1) ||'_'|| l.label
from gssurgo g, fields f, general_landuse l where o.gssurgo_id = g.id
and f.field_id = o.field_id and f.genlu = l.id ;
```
